version: '3.3'
services:
  # MongoDB service
  db:
    build:
      context: database/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    ports:
      - 27018:27018


  # Disposable service for seeding MongoDB with geolocation data
  db-seeder:
    build:
      context: database/
      dockerfile: Dockerfile-seeder
    depends_on:
      - db


  # OpenID Connect provider service
  oidc-provider:
    build:
      context: oidc-provider/
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Endpoints__Http__Url: http://*:5000
    ports:
      - 5000:5000


  # Web application service
  webapp:
    build:
      context: webapp/
    ports:
      - 3000:3000


  # Complaints API service
  complaints:
    build:
      context: complaints/
    ports:
      - 8080:8080


  # Complaints API service
  maps:
    build:
      context: maps/
    ports:
      - 8081:8081
