version: "3.7"
services:
  api:
    build: .
    image: ra-challenge
    ports:
      - 80:8080
    depends_on:
      - db
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    ports:
      - 12345:27017
    build:
      context: ./mongodb
      dockerfile: Dockerfile-mongodb