version: "3.7"
services:
  api:
    image: ra-challenge-api
    build:
      context: ./api
    ports:
      - 10123:8080
    depends_on:
      - db
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    ports:
      - 12345:27017
    build:
      context: ./database