version: "3.7"
services:
  api:
    image: ra-challenge-api
    build:
      context: ./api
    depends_on:
      - db
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    build:
      context: ./database
  webapp:
    image: ra-challenge-webapp
    environment:
      NODE_ENV: production
    build:
      context: ./webapp
    ports:
      - 80:3000
    depends_on:
      - db
      - api
  oidc-provider:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      ASPNETCORE_Kestrel__Endpoints__Http__Url: http://*:5000
    ports:
      - 5000:5000
    depends_on:
      - db
