version: '3.7'
services:
  oidc-provider:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    environment:
      ASPNETCORE_Kestrel__Endpoints__Http__Url: http://*:5000
    ports:
      - 5000:5000
    volumes:
      - ..:/workspace/oidc-provider:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - ra-challenge-dev
networks:
  ra-challenge-dev:
    name: ra-challenge-dev
    driver: bridge