version: '3.7'
services:
  api:
    image: ra-challenge-api
    build:
      context: ../
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ..:/workspace/api:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - ra-challenge-dev
networks:
  ra-challenge-dev:
    name: ra-challenge-dev
    driver: bridge