version: '3.7'
services:
  db:
    build:
      context: ../
      network: ra-challenge-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    ports:
      - 27018:27018
    networks:
      - ra-challenge-dev
networks:
  ra-challenge-dev:
    name: ra-challenge-dev
    driver: bridge