version: '3.7'
services:
  # MongoDB service
  db:
    build:
      context: ../
      network: ra-challenge-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
      MONGO_INITDB_DATABASE: ra_challenge
    ports:
      - 27018:27018
    networks:
      - ra-challenge-dev


  # Disposable service for seeding MongoDB with geolocation data
  db-seeder:
    build:
      context: ../
      dockerfile: Dockerfile-seeder
      network: ra-challenge-dev
    depends_on:
      - db
    networks:
      - ra-challenge-dev
networks:
  ra-challenge-dev:
    name: ra-challenge-dev
    driver: bridge